application: linkyourapp
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: static/foundation-5.3.0/css

- url: /img
  static_dir: static/foundation-5.3.0/img

- url: /js
  static_dir: static/foundation-5.3.0/js

- url: /.*
  script: _go_app